function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 04-May-2020 09:34:57

Fstop1 = 10000000;  % First Stopband Frequency
Fpass1 = 12500000;  % First Passband Frequency
Fpass2 = 17500000;  % Second Passband Frequency
Fstop2 = 20000000;  % Second Stopband Frequency
Astop1 = 50;        % First Stopband Attenuation (dB)
Apass  = 0.05;      % Passband Ripple (dB)
Astop2 = 50;        % Second Stopband Attenuation (dB)
Fs     = 60000000;  % Sampling Frequency

h = fdesign.decimator(3, 'Bandpass', 'fst1,fp1,fp2,fst2,ast1,ap,ast2', ...
    Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
    Astop2, Fs);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any', ...
    'SystemObject', true);


